# Generated by Django 6.0 on 2025-12-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='bairro',
            field=models.CharField(default=2, max_length=50, verbose_name='Bairro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occurrence',
            name='cep',
            field=models.CharField(default=1, max_length=9, verbose_name='CEP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occurrence',
            name='cidade',
            field=models.CharField(default=1, max_length=50, verbose_name='Cidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occurrence',
            name='logradouro',
            field=models.CharField(default=1, max_length=100, verbose_name='Logradouro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occurrence',
            name='numero',
            field=models.CharField(default=1, max_length=10, verbose_name='Número'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occurrence',
            name='uf',
            field=models.CharField(default=1, max_length=2, verbose_name='UF'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='latitude',
            field=models.DecimalField(decimal_places=6, help_text='Latitude em graus decimais', max_digits=9, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='longitude',
            field=models.DecimalField(decimal_places=6, help_text='Longitude em graus decimais', max_digits=9, verbose_name='Longitude'),
        ),
    ]
