# Generated by Django 6.0 on 2025-12-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0002_occurrence_bairro_occurrence_cep_occurrence_cidade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='occurrence',
            options={'ordering': ['occurred_at'], 'verbose_name': 'Denuncia', 'verbose_name_plural': 'Denuncias'},
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='numero',
        ),
        migrations.AddField(
            model_name='occurrence',
            name='reference',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
