# Generated by Django 6.0 on 2025-12-28 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0003_alter_occurrence_options_remove_occurrence_numero_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='occurrence',
            options={'ordering': ['-occurred_at'], 'verbose_name': 'Denuncia', 'verbose_name_plural': 'Denuncias'},
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='occurrence',
            index=models.Index(fields=['status'], name='occurrences_status_e3b4d6_idx'),
        ),
        migrations.AddIndex(
            model_name='occurrence',
            index=models.Index(fields=['crime_type'], name='occurrences_crime_t_51eeff_idx'),
        ),
        migrations.AddIndex(
            model_name='occurrence',
            index=models.Index(fields=['cidade', 'bairro'], name='occurrences_cidade_1a87e4_idx'),
        ),
        migrations.AddIndex(
            model_name='occurrence',
            index=models.Index(fields=['occurred_at'], name='occurrences_occurre_1e263d_idx'),
        ),
    ]
