# Generated by Django 6.0 on 2025-12-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0004_alter_occurrence_options_alter_occurrence_reporter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='crime_type',
            field=models.CharField(choices=[('theft', 'Furto'), ('robbery', 'Roubo'), ('assault', 'Agressão'), ('gunshot', 'Disparo de arma'), ('car', 'Acidente de trânsito'), ('other', 'Outro')], max_length=20),
        ),
    ]
