# Generated by Django 6.0 on 2025-12-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0005_alter_occurrence_crime_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='uf',
            field=models.CharField(max_length=20, verbose_name='UF'),
        ),
    ]
