# Generated by Django 6.0 on 2026-01-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0006_alter_occurrence_uf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='crime_type',
            field=models.CharField(choices=[('theft', 'Furto'), ('robbery', 'Roubo'), ('assault', 'Agressão'), ('gunshot', 'Disparo de arma'), ('car', 'Acidente de trânsito'), ('fire', 'incêndio'), ('other', 'Outro')], max_length=20),
        ),
    ]
