# Generated by Django 6.0 on 2026-01-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0007_alter_occurrence_crime_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='link',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
