# Generated by Django 6.0 on 2026-01-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
