# Generated by Django 6.0 on 2026-01-01 07:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0006_alter_occurrence_uf'),
        ('occurrencesvote', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='occurrencevote',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='occurrencevote',
            constraint=models.UniqueConstraint(fields=('occurrence', 'user'), name='unique_vote_per_user_per_occurrence'),
        ),
    ]
