# Generated by Django 6.0 on 2026-01-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrencesvote', '0002_alter_occurrencevote_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrencevote',
            name='vote',
            field=models.CharField(choices=[('confirm', 'Confirmo'), ('deny', 'Não procede'), ('unsure', 'Informação insuficiente'), ('reported', 'Já reportado')], max_length=10),
        ),
    ]
